media:
  input: public/images
  output: /public/images
  content:
  - name: 'events'
    label: 'الفعاليات'
    type: 'collection'
    path: 'data/events'
    filename: '{slug}.json'
    fields:
      - name: 'title:"KHUTBAH JUMUAAH"'
        label: 'عنوان الفعالية'
        type: 'string'
      - name: '"2026-05-22"'
        label: 'تاريخ الفعالية'
        type: 'date'
        options:
          format: 'YYYY-MM-DD'
      - name: '¨Khutbah en español y árabe'
        label: 'وصف الفعالية'
        type: 'text'
      - name: 'image'
        label: 'صورة الفعالية'
        type: 'image'
